version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "demo"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"